#!/usr/bin/env python

import sys
from dso3000 import *
from numpy import *

scope = DSO3000()

if len(sys.argv) < 3:
	print >> sys.stderr, 'Usage: %s <file> <channels...>' % sys.argv[0]
	sys.exit(1)

data = array([[]])
for ch in sys.argv[2:]:
	mem = scope.readMemory(int(ch))
	if not data.any():
		data.shape = (0, len(mem))
	data = append(data, [mem], 0)

savetxt(sys.argv[1], data)

