#!/usr/bin/python

import sys
import Image
from dso3000 import *

if len(sys.argv) != 2:
	# Any PIL-supported image format will work, but PNG is recommended.
	print >> sys.stderr, 'Usage: %s <output.png>' % sys.argv[0]
	sys.exit(1)

scope = DSO3000()
data = ''.join([chr(x) for x in scope.screenshot()])
im = Image.frombuffer('L', (320, 240), data, 'raw', 'L', 0, 1)
im.save(sys.argv[1])

